services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build: .
    env_file:
      - .env
    container_name: rq_worker
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - FRONTEND_BASE_URL=http://host.docker.internal:3000
      - CREWAI_STORAGE_DIR=./db

volumes:
  redis_data:
  static_data:
  templates_data:
